# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "fenced_code_blocks"]

# Permalinks
permalink:        pretty

# Setup
title:            Rahul Gopinath
tagline:          'Computer Science Researcher'
description:      ''
url:              http://www.vrtra.net

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/vrthra/vrthra.github.io
